### ISSUE TITLE
VSS Flow Generator Script Failing 

### ISSUE THREAD

**Issue by apooniajjn** [nuagenetworks/visualization-framework#781]
# VSS Flow Generator Script Failing Release 5.3.3

It seems when I am running VSS flow generator script which is failing.

## Error 

Error attached below: 

```
Writing flow information between PG4-VPort4 and PG5-VPort1
Traceback (most recent call last):
  File "./flowGenerator.py", line 132, in <module>
    generateFlowStats(i)
  File "./flowGenerator.py", line 96, in generateFlowStats
    writeToES(es_data)
  File "./flowGenerator.py", line 112, in writeToES
    helpers.bulk(es, iter(write_data), request_timeout=50)
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
```

Flowevent generator script works fine.

**Comment by apooniajjn** [comment]
I had to add a dummy value to resolve this error: `es_data['tcpstate'] = random.randint(10000, 20000)` in `writeToES(es_data)` function of `flowGenerator.py` file.
